services:
  backend:
    build: ./profile-manager-backend/.
    container_name: profilemanager-spring
    depends_on:
      - profilemanager-db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://profilemanager-db:5432/profilemanager-db"
      ALLOWED_ORIGINS: "http://localhost:9000"

  frontend:
    build: ./profile-manager-frontend/.
    container_name: profilemanager-angular
    ports:
      - 9000:9000

  profilemanager-db:
    container_name: profilemanager-db
    image: postgres:17-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    environment:
      POSTGRES_DB: profilemanager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./profilemanager_db:/var/lib/postgresql/data

volumes:
  profilemanager_db:
    driver: local

